name: Docker

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/gnx:latest,
              ghcr.io/${{ github.repository }}/gnx:${{ github.event.release.tag_name }}